// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/analytics-layouts/AnalyticsAcquisition.tsx": () => import("../components/mockups/analytics-layouts/AnalyticsAcquisition.tsx"),
  "./components/mockups/analytics-layouts/AnalyticsOverview.tsx": () => import("../components/mockups/analytics-layouts/AnalyticsOverview.tsx"),
  "./components/mockups/analytics-layouts/AnalyticsResponses.tsx": () => import("../components/mockups/analytics-layouts/AnalyticsResponses.tsx"),
  "./components/mockups/candidates-layouts/Clinic.tsx": () => import("../components/mockups/candidates-layouts/Clinic.tsx"),
  "./components/mockups/candidates-layouts/ObsidianIntelligence.tsx": () => import("../components/mockups/candidates-layouts/ObsidianIntelligence.tsx"),
  "./components/mockups/candidates-layouts/Papyrus.tsx": () => import("../components/mockups/candidates-layouts/Papyrus.tsx"),
  "./components/mockups/login-layouts/CommandDeck.tsx": () => import("../components/mockups/login-layouts/CommandDeck.tsx"),
  "./components/mockups/login-layouts/SplitScreen.tsx": () => import("../components/mockups/login-layouts/SplitScreen.tsx"),
  "./components/mockups/login-layouts/StackedBlocks.tsx": () => import("../components/mockups/login-layouts/StackedBlocks.tsx"),
  "./components/mockups/positions-layouts/CommandTable.tsx": () => import("../components/mockups/positions-layouts/CommandTable.tsx"),
  "./components/mockups/positions-layouts/NeuralGrid.tsx": () => import("../components/mockups/positions-layouts/NeuralGrid.tsx"),
  "./components/mockups/positions-layouts/PositionCreate.tsx": () => import("../components/mockups/positions-layouts/PositionCreate.tsx"),
  "./components/mockups/positions-layouts/PositionDetail.tsx": () => import("../components/mockups/positions-layouts/PositionDetail.tsx"),
  "./components/mockups/positions-layouts/PositionEdit.tsx": () => import("../components/mockups/positions-layouts/PositionEdit.tsx")
};
