// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/login-layouts/CommandDeck.tsx": () => import("../components/mockups/login-layouts/CommandDeck.tsx"),
  "./components/mockups/login-layouts/SplitScreen.tsx": () => import("../components/mockups/login-layouts/SplitScreen.tsx"),
  "./components/mockups/login-layouts/StackedBlocks.tsx": () => import("../components/mockups/login-layouts/StackedBlocks.tsx")
};
